version: 2

models:
  - name: films
    description: "This table contains details about films"
    columns:
      - name: film_id
        description: "Unique identifier for the film"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_date
        description: "Date the film was released"
        tests:
          - not_null
      - name: price
        description: "Price of the film"
        tests:
          - not_null
      - name: rating
        description: "MPA rating of the film (e.g., PG-13, R)"
        tests:
          - not_null
      - name: user_rating
        description: "Ratings by users"
        tests:
          - not_null

  - name: actors
    description: "Info about actors"
    columns:
      - name: actor_id
        description: "Unique identifier for actors"
        tests:
          - unique
          - not_null
      - name: actor_name
        description: "Name of the actor"
        tests:
          - not_null